### ISSUE TITLE
[Improvement]: Styling the input area

### ISSUE THREAD

**Issue by yaten2302** [ItIsOHM/gfi-notifier#11]
Hi @ItIsOHM, the input area can be styled by adding some borders on hover and on focus, it will give a better look to the website. 
![image](https://github.com/ItIsOHM/gfi-notifier/assets/129659514/955b3d9f-4de0-49de-9519-7a289ff78bf3)

Could you please assign this issue to me under SWOC.

**Comment by ItIsOHM** [comment]
Sure @yaten2302, you can start working on it :)

**Comment by yaten2302** [comment]
Hi @ItIsOHM, thanks for assigning this issue to me, I'll create the PR by tomorrow 👍
