### ISSUE TITLE
Enhancement in backend

### ISSUE THREAD

**Issue by Muhammad-Owais-Warsi** [ItIsOHM/gfi-notifier#12]
In this project's backend require() method is used to import the packages, instead we can use import statement as a good practice..

**Comment by ItIsOHM** [comment]
Sure @Muhammad-Owais-Warsi, we can do that. I'm assigning this issue to you :)

**Comment by Muhammad-Owais-Warsi** [comment]
> Sure @Muhammad-Owais-Warsi, we can do that. I'm assigning this issue to you :)

PR raised :)
