### ISSUE TITLE
feat:Confirm Password is missing

### ISSUE THREAD

**Issue by Niharika0104** [ItIsOHM/gfi-notifier#19]
In user registration page confirm password is missing.
I would like to fix this issue.
<img width="891" alt="snap11jan" src="https://github.com/ItIsOHM/gfi-notifier/assets/124892559/c4a7ee10-e5d8-4aba-8aaf-caca0d6df416">

**Comment by ItIsOHM** [comment]
This doesn't seem to be an issue related to GitAlert, @Niharika0104.
