### ISSUE TITLE
Bug: gfi-notifier showing repository not found for the existing repos too

### ISSUE THREAD

**Issue by yaten2302** [ItIsOHM/gfi-notifier#20]
Hi @ItIsOHM, when I searched for this repo, in the `gfi-notifier`, it showed the following ouput. <br>
![image](https://github.com/ItIsOHM/gfi-notifier/assets/129659514/05885064-3d8b-4203-b91b-49a1cfaa64c6)
<br>
When I was running this locally, my `env` file wasn't created. Is this issue because of the absence of the `env` variables or is it something else, could you please guide me regarding this.

**Comment by ItIsOHM** [comment]
The .env file is only needed if you're running the back-end too on your machine, but if you're only running the FE it's not really needed, since you're contacting the AWS backend. It's possible you're passing the wrong params to the backend due to which it's returning an error.

**Comment by yaten2302** [comment]
@ItIsOHM, the 2nd input box which is shown, it has nothing to do with the backend, I was trying to add a new feature, so I added the input box(only in frontend). Now, when I added my `GITHUB_ACCESS_TOKEN` in the `.env` file, it's again showing this error.
Here is my file structure. <br>
![image](https://github.com/ItIsOHM/gfi-notifier/assets/129659514/35149cde-ffa1-413b-bc87-59565902bb5c)

**Comment by ItIsOHM** [comment]
But why did you add the token to the .env file if you're only working on the FE? Can you please elaborate a little more as I'm not able to understand the problem you're facing.

**Comment by yaten2302** [comment]
https://github.com/ItIsOHM/gfi-notifier/assets/129659514/dc107994-aab1-4b48-8648-2e2e953e35eb

Sorry for being unclear @ItIsOHM , I was trying to ask that when I've put the repo url in the input box, it's showing that the repo doesn't exist(as shown in the video). Also, the `env` file was created and with my `GITHUB_ACCESS_TOKEN` in it.

**Comment by yaten2302** [comment]
> 2024-01-18.12-27-23.mp4 
> Sorry for being unclear @ItIsOHM , I was trying to ask that when I've put the repo url in the input box, it's showing that the repo doesn't exist(as shown in the video). Also, the `env` file was created and with my `GITHUB_ACCESS_TOKEN` in it.

Hey @ItIsOHM, is this issue clear or should I give some more explanation regarding this? Actually, I was working on a new feature, but without getting this issue fixed, I can't work on that.

**Comment by ItIsOHM** [comment]
@yaten2302 actually I was trying to recreate this on my machine but it's working fine. Can you share the code that you've added/modified, so that I can understand why that problem is being caused.

**Comment by yaten2302** [comment]
> @yaten2302 actually I was trying to recreate this on my machine but it's working fine. Can you share the code that you've added/modified, so that I can understand why that problem is being caused.

@ItIsOHM, I haven't changed anything in the code, I've just added my `GITHUB_ACCESS_TOKEN` in the `.env` file. Rest everything is same.

![image](https://github.com/ItIsOHM/gfi-notifier/assets/129659514/283d3dd7-cfae-4095-b404-b53c9778b856)

**Comment by yaten2302** [comment]
Also on the official website(not opened it locally), it's showing the same error.
![image](https://github.com/ItIsOHM/gfi-notifier/assets/129659514/1f99a78e-20de-4767-8a07-626d4bd0861c)

**Comment by ItIsOHM** [comment]
Okay upon further inspection, I think the issue is with the certification of the back-end. A workaround for this issue is to open the dev tools panel (usually by F12), go to the network tab, and on the website search for a repo. That'll show an error status code in the network tab. If you visit the URL that's being blocked, you'll see that the browser says it's unsafe to visit (since I don't currently have the proper certifications). On that page there should be an option present to allow the browser to contact the backend.

**Comment by yaten2302** [comment]
> Okay upon further inspection, I think the issue is with the certification of the back-end. A workaround for this issue is to open the dev tools panel (usually by F12), go to the network tab, and on the website search for a repo. That'll show an error status code in the network tab. If you visit the URL that's being blocked, you'll see that the browser says it's unsafe to visit (since I don't currently have the proper certifications). On that page there should be an option present to allow the browser to contact the backend.

Yes, I'm able to see the error status code, but after that where I've to visit? Could you please elaborate on this, I'm not able to understand it completely.

**Comment by ItIsOHM** [comment]
Unfortunately I don't have a machine right now with me where I can test the website, but as far as i remember if you visit "https://git-alert-server-dev.ap-south-1.elasticbeanstalk.com/" it should warn you with a connection not secure alert. If you allow that then hopefully the browser won't block your connection.

When you visit that link, it should show a `Hello World` message. It's the AWS EB instance's deployment.
