### ISSUE TITLE
fix: Issues tab doesn't disappear when clicking on about.

### ISSUE THREAD

**Issue by ItIsOHM** [ItIsOHM/gfi-notifier#9]
After displaying the issues on the main tab, if you click the about page the issues tab remains at the bottom.

Example: https://www.loom.com/share/7a2fabbcf84f47a0b0baca5b00a37a68?sid=7b104293-002e-485b-9c58-5dffa30e15d6

You need to fix this so that the issue tab doesn't show up in the about section.

**Comment by Rithvik9620** [comment]
Hi @ItIsOHM , I have raised a PR for this issue. Please review it.

**Comment by ItIsOHM** [comment]
@Rithvik9620 just a little heads up, when opening PRs, it's good to mention the issue in the PR body with the # which helps in automatically closing the corresponding issues like this one.
